version: '3'

services:
    db:
        image: mysql:5.7
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'comicsite'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'comicsitemysql123'
            MYSQL_ROOT_PASSWORD: 'comicsitemysql123'